# Generated by Django 5.2.4 on 2025-08-07 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='me_gusta',
            field=models.ManyToManyField(blank=True, related_name='comentarios_me_gusta', to=settings.AUTH_USER_MODEL),
        ),
    ]
