# Generated by Django 5.2.4 on 2025-08-11 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_recepcion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
